switchyard/release/karaf/features/src/main/resources/features.xml, switchyard/release/karaf/tests/pom.xml, switchyard/release/karaf/tests/src/test/java/org/switchyard/karaf/test/quickstarts/AbstractQuickstartTest.java, switchyard/release/karaf/tests/src/test/java/org/switchyard/karaf/test/quickstarts/BPMServiceQuickstartTest.java, switchyard/release/karaf/tests/src/test/java/org/switchyard/karaf/test/quickstarts/DeploymentProbe.java, switchyard/release/karaf/tests/src/test/java/org/switchyard/karaf/test/quickstarts/RulesCamelCBRQuickstartTest.java, switchyard/release/karaf/tests/src/test/java/org/switchyard/karaf/test/quickstarts/RulesInterviewContainerQuickstartTest.java, switchyard/release/karaf/tests/src/test/java/org/switchyard/karaf/test/quickstarts/RulesInterviewDTableQuickstartTest.java, switchyard/release/karaf/tests/src/test/java/org/switchyard/karaf/test/quickstarts/RulesInterviewQuickstartTest.java, switchyard/release/karaf/tests/src/test/java/org/switchyard/karaf/test/quickstarts/demo/HelpdeskDemoQuickstartTest.java, switchyard/release/karaf/tests/src/test/java/org/switchyard/karaf/test/quickstarts/demo/LibraryDemoQuickstartTest.java
https://issues.jboss.org/browse/ENTESB-2803
=> ENTESB-2803  Switchyard release Karaf tests failing

karaf/features/src/main/resources/features.xml, karaf/tests/switchyard/src/test/java/org/switchyard/karaf/test/quickstarts/AbstractQuickstartTest.java, karaf/tests/switchyard/src/test/java/org/switchyard/karaf/test/quickstarts/BPMServiceQuickstartTest.java, karaf/tests/switchyard/src/test/java/org/switchyard/karaf/test/quickstarts/DeploymentProbe.java, karaf/tests/switchyard/src/test/java/org/switchyard/karaf/test/quickstarts/RulesCamelCBRQuickstartTest.java, karaf/tests/switchyard/src/test/java/org/switchyard/karaf/test/quickstarts/RulesInterviewContainerQuickstartTest.java, karaf/tests/switchyard/src/test/java/org/switchyard/karaf/test/quickstarts/RulesInterviewDTableQuickstartTest.java, karaf/tests/switchyard/src/test/java/org/switchyard/karaf/test/quickstarts/RulesInterviewQuickstartTest.java, karaf/tests/switchyard/src/test/java/org/switchyard/karaf/test/quickstarts/demo/HelpdeskDemoQuickstartTest.java, karaf/tests/switchyard/src/test/java/org/switchyard/karaf/test/quickstarts/demo/LibraryDemoQuickstartTest.java, release/jboss-as7/modules/src/main/resources/switchyard/components/bpm/assembly-component.xml, release/jboss-as7/modules/src/main/resources/switchyard/components/common/knowledge/assembly-component.xml, release/jboss-as7/modules/src/main/resources/switchyard/components/rules/assembly-component.xml
https://issues.jboss.org/browse/ENTESB-2921
=> ENTESB-2921  karaf bxms packages update

release/jboss-as7/modules/src/main/resources/layers.conf
https://issues.jboss.org/browse/ENTESB-2973
=> ENTESB-2973 Fix jboss eap switchyard brms deployment

quickstarts/switchyard-quickstarts-assembly/assembly.xml, quickstarts/switchyard-quickstarts-assembly/src/main/resources/pom.xml, release/eap/fuse-integration-eap-distro/src/main/resources/build.xml, release/eap/fuse-integration-eap-tests/pom.xml, release/eap/fuse-integration-eap-tests/src/test/java/org/switchyard/test/quickstarts/util/BRMSArquillianUtil.java
https://issues.jboss.org/browse/ENTESB-3021
=> ENTESB-3021  errors in the distro build

quickstarts/fuse-integration-quickstarts-eap/assembly.xml, quickstarts/fuse-integration-quickstarts-eap/src/main/resources/pom.xml, quickstarts/fuse-integration-quickstarts-karaf/assembly.xml, quickstarts/fuse-integration-quickstarts-karaf/src/main/resources/pom.xml
https://issues.jboss.org/browse/ENTESB-3047
=> ENTESB-3047  pom eap assembly version not correct

release/eap/fuse-integration-eap-xslt/pom.xml, release/eap/fuse-integration-eap-xslt/src/main/resources/xsl/domain_disable.xsl, release/eap/fuse-integration-eap-xslt/src/main/resources/xsl/domain_enable.xsl, release/eap/fuse-integration-eap-xslt/src/main/resources/xsl/standalone_disable.xsl
https://issues.jboss.org/browse/ENTESB-3063
=> ENTESB-3063  Refactor eap distro: remove ant requirement

pom.xml, release/eap/fuse-integration-eap-distro/assembly.xml, release/eap/fuse-integration-eap-distro/pom.xml, release/eap/fuse-integration-eap-modules/pom.xml, release/eap/fuse-integration-eap-tests/pom.xml, release/eap/pom.xml
https://issues.jboss.org/browse/ENTESB-3066
=> Entesb 3066

switchyard/switchyard-component-common-knowledge/src/main/java/org/switchyard/component/common/knowledge/config/builder/RuntimeEnvironmentBuilder.java, switchyard/switchyard-component-common-knowledge/src/main/java/org/switchyard/component/common/knowledge/runtime/KnowledgeRuntimeManager.java
https://issues.jboss.org/browse/ENTESB-3017
=> ENTESB-3017 Rules component is not updated after change of Kie project

pom.xml, switchyard/switchyard-component-common-knowledge/src/main/java/org/switchyard/component/common/knowledge/config/builder/RemoteConfigurationBuilder.java
https://issues.jboss.org/browse/ENTESB-3291
=> Revert the change related upgrade to kie 6.3.x

quickstarts/fuse-integration-quickstarts-eap/assembly.xml, quickstarts/fuse-integration-quickstarts-karaf/assembly.xml, quickstarts/karaf-features/src/main/resources/features.xml, quickstarts/pom.xml, quickstarts/switchyard-rules-multithreaded/Readme.md, quickstarts/switchyard-rules-multithreaded/pom.xml, quickstarts/switchyard-rules-multithreaded/src/main/java/org/switchyard/quickstarts/rules/multi/CustomComposer.java, quickstarts/switchyard-rules-multithreaded/src/main/java/org/switchyard/quickstarts/rules/multi/Item.java, quickstarts/switchyard-rules-multithreaded/src/main/java/org/switchyard/quickstarts/rules/multi/OrderDecision.java, quickstarts/switchyard-rules-multithreaded/src/main/java/org/switchyard/quickstarts/rules/multi/OrderResource.java, quickstarts/switchyard-rules-multithreaded/src/main/java/org/switchyard/quickstarts/rules/multi/OrderService.java, quickstarts/switchyard-rules-multithreaded/src/main/java/org/switchyard/quickstarts/rules/multi/OrderServiceImpl.java, quickstarts/switchyard-rules-multithreaded/src/main/java/org/switchyard/quickstarts/rules/multi/Transformers.java, quickstarts/switchyard-rules-multithreaded/src/main/java/org/switchyard/quickstarts/rules/multi/Warehouse.java, quickstarts/switchyard-rules-multithreaded/src/main/java/org/switchyard/quickstarts/rules/multi/WarehouseResource.java, quickstarts/switchyard-rules-multithreaded/src/main/java/org/switchyard/quickstarts/rules/multi/WarehouseService.java, quickstarts/switchyard-rules-multithreaded/src/main/java/org/switchyard/quickstarts/rules/multi/WarehouseServiceImpl.java, quickstarts/switchyard-rules-multithreaded/src/main/resources/META-INF/beans.xml, quickstarts/switchyard-rules-multithreaded/src/main/resources/META-INF/switchyard.xml, quickstarts/switchyard-rules-multithreaded/src/main/resources/RulesComponent.drl, quickstarts/switchyard-rules-multithreaded/src/test/java/org/switchyard/quickstarts/rules/multi/RulesMultiThreadBindingUtils.java, quickstarts/switchyard-rules-multithreaded/src/test/java/org/switchyard/quickstarts/rules/multi/RulesMultithreadBindingClient.java, quickstarts/switchyard-rules-multithreaded/src/test/resources/META-INF/beans.xml, quickstarts/switchyard-rules-multithreaded/src/test/resources/META-INF/services/org.switchyard.component.resteasy.resource.ResourcePublisher, quickstarts/switchyard-rules-multithreaded/src/test/resources/log4j.xml, release/karaf/fuse-integration-karaf-distro/pom.xml
https://issues.jboss.org/browse/ENTESB-3247
=> ENTESB-3247

karaf/karaf-features/src/main/resources/features.xml, pom.xml, quickstarts/karaf-features/src/main/resources/features.xml, quickstarts/switchyard-bpm-service/Readme.md, quickstarts/switchyard-demo-helpdesk/Readme.md, quickstarts/switchyard-demo-library/Readme.md, quickstarts/switchyard-rules-camel-cbr/Readme.md, quickstarts/switchyard-rules-interview-container/Readme.md, quickstarts/switchyard-rules-interview-dtable/Readme.md, quickstarts/switchyard-rules-interview/Readme.md, quickstarts/switchyard-rules-multithreaded/Readme.md, release/karaf/fuse-integration-karaf-tests/drools/pom.xml, release/karaf/fuse-integration-karaf-tests/drools/src/test/java/org/drools/karaf/itest/DroolsOnBodyCamelKarafIntegrationTest.java, release/karaf/fuse-integration-karaf-tests/drools/src/test/java/org/drools/karaf/itest/DroolsOnCommandCamelKarafIntegrationTest.java, release/karaf/fuse-integration-karaf-tests/drools/src/test/java/org/drools/karaf/itest/KarafIntegrationTestSupport.java, release/karaf/fuse-integration-karaf-tests/drools/src/test/java/org/drools/karaf/itest/KieSpringIntegrationTestSupport.java, release/karaf/fuse-integration-karaf-tests/drools/src/test/java/org/drools/karaf/itest/KieSpringOnKarafIntegrationTest.java, release/karaf/fuse-integration-karaf-tests/drools/src/test/java/org/drools/karaf/itest/KieSpringjBPMPersistenceOnKarafIntegrationTest.java, release/karaf/fuse-integration-karaf-tests/switchyard/pom.xml, release/karaf/fuse-integration-karaf-tests/switchyard/src/test/java/org/switchyard/karaf/test/quickstarts/AbstractQuickstartTest.java
ENTESB-3283  Remove drools and swithcyard features repositories
=> ENTESB-3283 Remove drools and swithcyard features repositories

switchyard/switchyard-component-bpm/src/main/java/org/switchyard/component/bpm/exchange/BPMExchangeHandler.java
https://issues.jboss.org/browse/ENTESB-3339
=> ENTESB-3339  Mapping from unset data item doesn't work in BPM

quickstarts/switchyard-bpm-service/Readme.md, quickstarts/switchyard-demo-helpdesk/Readme.md, quickstarts/switchyard-demo-library/Readme.md, quickstarts/switchyard-rules-camel-cbr/Readme.md, quickstarts/switchyard-rules-interview-container/Readme.md, quickstarts/switchyard-rules-interview-dtable/Readme.md, quickstarts/switchyard-rules-interview/Readme.md, quickstarts/switchyard-rules-multithreaded/Readme.md
https://issues.jboss.org/browse/ENTESB-3358
=> ENTESB-3358 Add Fuse Installation chapter on the quickstart README files

karaf/karaf-features/pom.xml, quickstarts/karaf-features/pom.xml
https://issues.jboss.org/browse/ENTESB-3094
=> ENTESB-3094 HelpDesk Demo not working on fuse karaf 6.2.0.redhat.099

camel/kie-camel/pom.xml, quickstarts/fuse-integration-quickstarts-karaf/assembly.xml, quickstarts/fuse-integration-quickstarts-karaf/src/main/resources/pom.xml, quickstarts/karaf-features/src/main/resources/features.xml, release/karaf/fuse-integration-karaf-distro/pom.xml, release/karaf/fuse-integration-karaf-tests/drools/src/test/java/org/drools/karaf/itest/KieSpringjBPMPersistenceOnKarafIntegrationTest.java
https://issues.jboss.org/browse/ENTESB-3438
=> ENTESB-3438 Align changes of fuse-integration with master

pom.xml, release/karaf/fuse-integration-karaf-distro/pom.xml
https://issues.jboss.org/browse/ENTESB-3474
=> ENTESB-3474 Restore the resources generation on karaf distro

camel/jbpm-workitems-camel/pom.xml, camel/kie-camel/pom.xml, karaf/karaf-features/pom.xml, karaf/karaf-features/src/main/resources/features.xml, pom.xml, quickstarts/karaf-features/src/main/resources/features.xml
https://issues.jboss.org/browse/ENTESB-3483
=> ENTESB-3483 Increase osgi version ranges for cxf and camel

camel/jbpm-workitems-camel/pom.xml, karaf/karaf-features/src/main/resources/features.xml, release/karaf/fuse-integration-karaf-distro/assembly.xml, release/karaf/fuse-integration-karaf-distro/pom.xml
https://issues.jboss.org/browse/ENTESB-3509
=> ENTESB-3509 Exclude drools artifacts from Fuse Karaf Distro

release/karaf/fuse-integration-karaf-distro/assembly.xml
https://issues.jboss.org/browse/ENTESB-3510
=> ENTESB-3510 Modify distro karaf to put the quickstarts on another folder

quickstarts/fuse-integration-quickstarts-eap/assembly.xml, quickstarts/fuse-integration-quickstarts-karaf/assembly.xml, quickstarts/karaf-features/src/main/resources/features.xml, quickstarts/pom.xml, release/eap/itests/src/test/java/org/switchyard/test/quickstarts/demo/HelpDeskDemoQuickstartTest.java
https://issues.jboss.org/browse/ENTESB-3540
=> ENTESB-3540  Comment the Helpdesk quickstart

camel/kie-camel/src/main/java/org/kie/camel/component/XStreamXml.java, pom.xml, release/eap/installer/pom.xml, release/karaf/fuse-integration-karaf-tests/drools/pom.xml, release/pom.xml, release/standalone/kie-standalone-package/pom.xml, switchyard/switchyard-component-common-knowledge/src/main/java/org/switchyard/component/common/knowledge/config/builder/RemoteConfigurationBuilder.java, switchyard/switchyard-component-common-knowledge/src/main/java/org/switchyard/component/common/knowledge/runtime/KnowledgeRuntimeManager.java, switchyard/switchyard-component-common-knowledge/src/main/java/org/switchyard/component/common/knowledge/runtime/remote/RemoteRuntimeManager.java
https://issues.jboss.org/browse/ENTESB-3544
=> ENTESB-3544 Upgrade the Kie version to 6.3.0-SNAPSHOT

pom.xml, quickstarts/jbpm-workitems-camel/ReadMe.md, quickstarts/jbpm-workitems-camel/pom.xml, quickstarts/jbpm-workitems-camel/src/main/java/org/jboss/integration/fuse/quickstarts/jbpm/workitems/camel/Activator.java, quickstarts/jbpm-workitems-camel/src/main/java/org/jboss/integration/fuse/quickstarts/jbpm/workitems/camel/MortgageApplication.java, quickstarts/jbpm-workitems-camel/src/main/resources/META-INF/kmodule.xml, quickstarts/jbpm-workitems-camel/src/main/resources/org/jboss/integration/fuse/quickstarts/jbpm/workitems/camel/BPMN2-CamelFileProcess.bpmn2, quickstarts/jbpm-workitems-camel/src/main/resources/org/jboss/integration/fuse/quickstarts/jbpm/workitems/camel/CamelWorkDefinitions.wid, quickstarts/karaf-features/src/main/resources/features.xml, quickstarts/pom.xml
[ENTESB-3543] Include quickstart for the jbpm-workitems-camel functionality.
=> [ENTESB-3543] Include quickstart for the jbpm-workitems-camel

quickstarts/blueprint-camel-drools-decision-table/pom.xml, quickstarts/drools-camel-server-example/pom.xml, quickstarts/fuse-integration-quickstarts-karaf/assembly.xml, quickstarts/spring-camel-drools-decision-table/pom.xml, quickstarts/switchyard-bpm-service/pom.xml, quickstarts/switchyard-demo-helpdesk/pom.xml, quickstarts/switchyard-demo-library/pom.xml, quickstarts/switchyard-drools-channels/pom.xml, quickstarts/switchyard-example-rules-kie/pom.xml, quickstarts/switchyard-rules-camel-cbr/pom.xml, quickstarts/switchyard-rules-csv/pom.xml, quickstarts/switchyard-rules-interview-container/pom.xml, quickstarts/switchyard-rules-interview-dtable/pom.xml, quickstarts/switchyard-rules-interview/pom.xml, quickstarts/switchyard-rules-multithreaded/pom.xml
https://issues.jboss.org/browse/ENTESB-3711
=> ENTESB-3711  Restore groupId on quickstarts

pom.xml, release/karaf/distro/assembly.xml, release/karaf/distro/pom.xml
https://issues.jboss.org/browse/ENTESB-3719
=> ENTESB-3719 Add quickstarts feature file to the karaf distro

karaf/karaf-features/src/main/resources/features.xml, pom.xml, switchyard/switchyard-component-common-knowledge/src/main/java/org/switchyard/component/common/knowledge/runtime/KnowledgeRuntimeManager.java, switchyard/switchyard-component-common-knowledge/src/main/java/org/switchyard/component/common/knowledge/runtime/remote/RemoteRuntimeManager.java
https://issues.jboss.org/browse/ENTESB-3733
=> Entesb 3733

README.md
https://issues.jboss.org/browse/ENTESB-3736
=> ENTESB-3736 Update and Improve the Readme files

switchyard/switchyard-component-bpm/src/main/java/org/switchyard/component/bpm/exchange/BPMExchangeHandler.java
https://issues.jboss.org/browse/ENTESB-3744
=> ENTESB-3744  Regression in BPM component fault handling

quickstarts/karaf-features/src/main/resources/features.xml
https://issues.jboss.org/browse/ENTESB-3757
=> ENTESB-3757 Fix error on features.xml on the 1.0.x branch

pom.xml, quickstarts/blueprint-camel-drools-decision-table/pom.xml, quickstarts/drools-camel-server-example/pom.xml, quickstarts/jbpm-workitems-camel/pom.xml, quickstarts/pom.xml, quickstarts/spring-camel-drools-decision-table/pom.xml, quickstarts/switchyard-bpm-service/pom.xml, quickstarts/switchyard-demo-helpdesk/pom.xml, quickstarts/switchyard-demo-library/pom.xml, quickstarts/switchyard-drools-channels/pom.xml, quickstarts/switchyard-rules-camel-cbr/pom.xml, quickstarts/switchyard-rules-csv/pom.xml, quickstarts/switchyard-rules-interview-container/pom.xml, quickstarts/switchyard-rules-interview-dtable/pom.xml, quickstarts/switchyard-rules-interview/pom.xml, quickstarts/switchyard-rules-multithreaded/pom.xml, release/eap/itests/src/test/java/org/switchyard/test/quickstarts/RulesLoadingQuickstartTest.java
https://issues.jboss.org/browse/ENTESB-3768
=> ENTESB-3768  Add repositories to quickstarts

pom.xml, quickstarts/blueprint-camel-drools-decision-table/pom.xml, quickstarts/drools-camel-server-example/pom.xml, quickstarts/jbpm-workitems-camel/pom.xml, quickstarts/spring-camel-drools-decision-table/pom.xml, quickstarts/switchyard-bpm-service/pom.xml, quickstarts/switchyard-demo-helpdesk/pom.xml, quickstarts/switchyard-demo-library/pom.xml, quickstarts/switchyard-drools-channels/pom.xml, quickstarts/switchyard-rules-camel-cbr/pom.xml, quickstarts/switchyard-rules-csv/pom.xml, quickstarts/switchyard-rules-interview-container/pom.xml, quickstarts/switchyard-rules-interview-dtable/pom.xml, quickstarts/switchyard-rules-interview/pom.xml, quickstarts/switchyard-rules-multithreaded/pom.xml
https://issues.jboss.org/browse/ENTESB-3775
=>     ENTESB-3775 Include SCM, URL and Developer info in the quickstarts

pom.xml
https://issues.jboss.org/browse/ENTESB-3788
=> ENTESB-3788 Update camel sap version

quickstarts/fuse-integration-quickstarts-eap/assembly.xml, quickstarts/fuse-integration-quickstarts-karaf/assembly.xml
https://issues.jboss.org/browse/ENTESB-3789
=> ENTESB-3789  Modify the karaf distro quickstarts

quickstarts/switchyard-bpm-service/Readme.md, quickstarts/switchyard-demo-helpdesk/Readme.md, quickstarts/switchyard-demo-library/Readme.md, quickstarts/switchyard-rules-camel-cbr/Readme.md, quickstarts/switchyard-rules-interview-container/Readme.md, quickstarts/switchyard-rules-interview-dtable/Readme.md, quickstarts/switchyard-rules-interview/Readme.md, quickstarts/switchyard-rules-multithreaded/Readme.md
https://issues.jboss.org/browse/ENTESB-3791
=> ENTESB-3791 Modify README quickstarts

karaf/karaf-features/pom.xml, pom.xml, quickstarts/karaf-features/pom.xml
https://issues.jboss.org/browse/ENTESB-3471
=> ENTESB-3471 Improve features file

switchyard/switchyard-component-common-knowledge/src/main/java/org/switchyard/component/common/knowledge/persistence/EntityManagerFactoryLoader.java
https://issues.jboss.org/browse/ENTESB-4008
=> ENTESB-4008 Incompabilities hibernate-osgi and geronimo_jpa_2_0 on fuse

pom.xml
https://issues.jboss.org/browse/ENTESB-4020
=> ENTESB-4020 aether-api version needs to be included on parent pom

pom.xml
https://issues.jboss.org/browse/ENTESB-4091
=> ENTESB-4091 Upgrade fuse-integration drools version in master

pom.xml
https://issues.jboss.org/browse/ENTESB-4126
=> ENTESB-4126 Upgrade cdi-weld version to align with switchyard

camel/kie-camel/src/test/java/org/kie/camel/component/BatchTest.java, camel/kie-camel/src/test/java/org/kie/camel/component/CamelEndpointWithJaxWrapperCollectionTest.java, camel/kie-camel/src/test/java/org/kie/camel/component/CamelEndpointWithJaxbTest.java, camel/kie-camel/src/test/java/org/kie/camel/component/CamelEndpointWithJaxbXSDModelTest.java, camel/kie-camel/src/test/java/org/kie/camel/component/JaxbInsertTest.java, camel/kie-camel/src/test/java/org/kie/camel/component/JaxbTest.java, camel/kie-camel/src/test/java/org/kie/camel/component/KieCamelTestSupport.java, camel/kie-camel/src/test/java/org/kie/camel/component/XStreamBatchExecutionTest.java, camel/kie-camel/src/test/java/org/kie/camel/component/cxf/CxfRestTest.java, camel/kie-camel/src/test/java/org/kie/camel/component/cxf/CxfRestTestWithImport.java, camel/kie-camel/src/test/java/org/kie/camel/component/cxf/CxfRestTestWithLookup.java, camel/kie-camel/src/test/resources/org/kie/camel/component/jaxb.mvt, camel/kie-camel/src/test/resources/org/kie/camel/component/json.mvt, camel/kie-camel/src/test/resources/org/kie/camel/component/xstream.mvt, switchyard/switchyard-component-common-knowledge/src/main/java/org/switchyard/component/common/knowledge/config/builder/RemoteConfigurationBuilder.java, switchyard/switchyard-component-rules/src/main/java/org/switchyard/component/rules/exchange/RulesExchangeHandler.java
Depends on https://github.com/droolsjbpm/drools/pull/540
Solves: https://bugzilla.redhat.com/show_bug.cgi?id=1267906
=> ENTESB-4090 - Fixing fuse integration (Fuse hack breaks kie-remote-client usage in Fuse code)

release/eap/itests/src/test/java/org/switchyard/test/quickstarts/RulesLoadingQuickstartTest.java
https://issues.jboss.org/browse/ENTESB-4360
=> ENTESB-4360 Rules Loading itest remove @Ignore

pom.xml, release/karaf/fuse-integration-karaf-distro/README_FUSE_INTEGRATION.md
This is very similar to https://github.com/jboss-integration/fuse-bxms-integ/pull/173
Please have a look.
We hope this can be merge before the next tag for next patch release.
=> Polish the readme and upgrade eap version

pom.xml, release/pom.xml
https://issues.jboss.org/browse/ENTESB-4621
=> ENTESB-4621 Branch 1.2.x should point to fuse 6.2.0

pom.xml, release/eap/modules/pom.xml, release/karaf/itests/switchyard/pom.xml
This is for fixing https://issues.jboss.org/browse/ENTESB-4720
=> Fix entesb 4720

camel/pom.xml
This is a proposed solution for fixing https://issues.jboss.org/browse/ENTESB-4719
Please have a look that if it makes sense.
=> Fix entesb 4719

camel/pom.xml
Import jboss-fuse-parent  in fuse-integration-project and remove the… dependencymanagement in camel module
=> Fix entesb 4719 on 1.2.x branch

camel/pom.xml
Import jboss-fuse-parent  in fuse-integration-project and remove the…dependencymanagement in camel module
=>  Fix ENTESB-4719 on 1.1.x branches

quickstarts/fuse-integration-quickstarts-karaf/assembly.xml
https://issues.jboss.org/browse/ENTESB-4774?filter=-1
=> ENTESB-4774 Missing quickstart source codes

fuse-integration-bom/pom.xml, pom.xml, quickstarts/blueprint-camel-drools-decision-table/pom.xml, quickstarts/drools-camel-server-example/pom.xml, quickstarts/jbpm-workitems-camel/pom.xml, quickstarts/spring-camel-drools-decision-table/pom.xml, quickstarts/switchyard-bpm-service/pom.xml, quickstarts/switchyard-demo-helpdesk/pom.xml, quickstarts/switchyard-demo-library/pom.xml, quickstarts/switchyard-drools-channels/pom.xml, quickstarts/switchyard-rules-camel-cbr/pom.xml, quickstarts/switchyard-rules-csv/pom.xml, quickstarts/switchyard-rules-interview-container/pom.xml, quickstarts/switchyard-rules-interview-dtable/pom.xml, quickstarts/switchyard-rules-interview/pom.xml, quickstarts/switchyard-rules-loading/pom.xml, quickstarts/switchyard-rules-multithreaded/pom.xml
* remove remote repositories which are not needed for the build.
Tested with empty local maven repo (~./m2/repository)
* use plugin versions coming from ip-parent
* fix typo Commiters -> Committers
* fix indenting - use 4 spaces
=> Clean-up top-level pom and fuse-integration-bom

fuse-integration-bom/pom.xml, pom.xml
* applying to make cherry-picks from master easier
=> Fix indentation in top-level POM and BOM

fuse-integration-bom/pom.xml, quickstarts/blueprint-camel-drools-decision-table/pom.xml, quickstarts/jbpm-workitems-camel/pom.xml, quickstarts/spring-camel-drools-decision-table/pom.xml, quickstarts/spring-jbpm-osgi-example/pom.xml, quickstarts/switchyard-bpm-service/pom.xml, quickstarts/switchyard-demo-helpdesk/pom.xml, quickstarts/switchyard-demo-library/pom.xml, quickstarts/switchyard-drools-channels/pom.xml, quickstarts/switchyard-rules-camel-cbr/pom.xml, quickstarts/switchyard-rules-csv/pom.xml, quickstarts/switchyard-rules-interview-container/pom.xml, quickstarts/switchyard-rules-interview-dtable/pom.xml, quickstarts/switchyard-rules-interview/pom.xml, quickstarts/switchyard-rules-loading/pom.xml, quickstarts/switchyard-rules-multithreaded/pom.xml
https://issues.jboss.org/browse/ENTESB-4835
=> ENTESB-4835 Avoid parent pom on fuse-bxms-integ bom project

quickstarts/spring-jbpm-osgi-example/pom.xml, quickstarts/switchyard-rules-loading/pom.xml
https://issues.jboss.org/browse/ENTESB-4871
=> ENTESB-4871 Quickstarts missing maven attributes

quickstarts/spring-camel-drools-decision-table/ReadMe.md, quickstarts/switchyard-rules-multithreaded/Readme.md
**https://issues.jboss.org/browse/ENTESB-4931**
=> ENTESB-4931 Wrong feature names in quickstart Readme

release/karaf/distro/README_FUSE_INTEGRATION.md
https://issues.jboss.org/browse/ENTESB-4986
=> ENTESB-4986 Correct installation instructions for integration-pack

quickstarts/karaf-features/src/main/resources/features.xml, quickstarts/switchyard-drools-channels/Readme.md, quickstarts/switchyard-drools-channels/pom.xml, quickstarts/switchyard-drools-channels/src/main/java/org/switchyard/quickstarts/channels/Channel.java, quickstarts/switchyard-drools-channels/src/main/java/org/switchyard/quickstarts/channels/WorkerA.java, quickstarts/switchyard-drools-channels/src/main/java/org/switchyard/quickstarts/channels/WorkerABean.java, quickstarts/switchyard-drools-channels/src/main/java/org/switchyard/quickstarts/channels/WorkerB.java, quickstarts/switchyard-drools-channels/src/main/resources/META-INF/switchyard.xml, quickstarts/switchyard-drools-channels/src/test/java/org/switchyard/quickstarts/channels/ChannelsTest.java
https://issues.jboss.org/browse/ENTESB-4929
=> ENTESB-4929 Drools channels not working on karaf

quickstarts/blueprint-camel-drools-decision-table/ReadMe.md, quickstarts/jbpm-workitems-camel/ReadMe.md, quickstarts/spring-camel-drools-decision-table/ReadMe.md
* this is just very basic text, to have something in there,
until the Spring/Blueprint quickstarts are properly fixed.
They need polishing as well as better domain (instead of
the toy cheese/drink stuff) to show the integration features.
=> [ENTESB-4991] add basic QS description where needed

quickstarts/blueprint-camel-drools-decision-table/pom.xml, quickstarts/jbpm-workitems-camel/pom.xml, quickstarts/spring-camel-drools-decision-table/pom.xml, quickstarts/spring-jbpm-osgi-example/pom.xml, quickstarts/switchyard-bpm-service/pom.xml, quickstarts/switchyard-demo-helpdesk/pom.xml, quickstarts/switchyard-demo-library/pom.xml, quickstarts/switchyard-drools-channels/pom.xml, quickstarts/switchyard-rules-camel-cbr/pom.xml, quickstarts/switchyard-rules-csv/pom.xml, quickstarts/switchyard-rules-interview-container/pom.xml, quickstarts/switchyard-rules-interview-dtable/pom.xml, quickstarts/switchyard-rules-interview/pom.xml, quickstarts/switchyard-rules-loading/pom.xml, quickstarts/switchyard-rules-multithreaded/pom.xml
https://issues.jboss.org/browse/ENTESB-5090
=> ENTESB-5090 Add kie repository on the quickstarts

quickstarts/blueprint-camel-drools-decision-table/pom.xml, quickstarts/jbpm-workitems-camel/pom.xml, quickstarts/spring-camel-drools-decision-table/pom.xml, quickstarts/spring-jbpm-osgi-example/pom.xml, quickstarts/switchyard-bpm-service/pom.xml, quickstarts/switchyard-demo-helpdesk/pom.xml, quickstarts/switchyard-demo-library/pom.xml, quickstarts/switchyard-drools-channels/pom.xml, quickstarts/switchyard-rules-camel-cbr/pom.xml, quickstarts/switchyard-rules-csv/pom.xml, quickstarts/switchyard-rules-interview-container/pom.xml, quickstarts/switchyard-rules-interview-dtable/pom.xml, quickstarts/switchyard-rules-interview/pom.xml, quickstarts/switchyard-rules-loading/pom.xml, quickstarts/switchyard-rules-multithreaded/pom.xml
https://issues.jboss.org/browse/ENTESB-5090
=> Correct BXMS Repository.

pom.xml
https://issues.jboss.org/browse/ENTESB-5096
=> ENTESB-5096 Remove private repositories from 1.3.x and 1.4.x

README.md, quickstarts/blueprint-camel-drools-decision-table/ReadMe.md, quickstarts/karaf-features/src/main/resources/features.xml, quickstarts/spring-camel-drools-decision-table/ReadMe.md, quickstarts/switchyard-bpm-service/Readme.md, quickstarts/switchyard-demo-helpdesk/Readme.md, quickstarts/switchyard-demo-library/Readme.md, quickstarts/switchyard-drools-channels/Readme.md, quickstarts/switchyard-rules-camel-cbr/Readme.md, quickstarts/switchyard-rules-csv/ReadMe.md, quickstarts/switchyard-rules-interview-container/Readme.md, quickstarts/switchyard-rules-interview-dtable/Readme.md, quickstarts/switchyard-rules-interview/Readme.md, quickstarts/switchyard-rules-multithreaded/Readme.md, release/karaf/distro/README_FUSE_INTEGRATION.md, release/karaf/distro/pom.xml, release/karaf/itests/switchyard/src/test/java/org/switchyard/karaf/test/quickstarts/BPMServiceQuickstartTest.java, release/karaf/itests/switchyard/src/test/java/org/switchyard/karaf/test/quickstarts/CSVRulesQuickstartTest.java, release/karaf/itests/switchyard/src/test/java/org/switchyard/karaf/test/quickstarts/RulesCamelCBRQuickstartTest.java, release/karaf/itests/switchyard/src/test/java/org/switchyard/karaf/test/quickstarts/RulesInterviewContainerQuickstartTest.java, release/karaf/itests/switchyard/src/test/java/org/switchyard/karaf/test/quickstarts/RulesInterviewDTableQuickstartTest.java, release/karaf/itests/switchyard/src/test/java/org/switchyard/karaf/test/quickstarts/RulesInterviewQuickstartTest.java, release/karaf/itests/switchyard/src/test/java/org/switchyard/karaf/test/quickstarts/demo/HelpdeskDemoQuickstartTest.java, release/karaf/itests/switchyard/src/test/java/org/switchyard/karaf/test/quickstarts/demo/LibraryDemoQuickstartTest.java
https://issues.jboss.org/browse/ENTESB-5123
=> ENTESB-5123 Modify quickstarts Features names

quickstarts/switchyard-demo-helpdesk/pom.xml, quickstarts/switchyard-demo-helpdesk/src/main/resources/META-INF/persistence-osgi.xml, quickstarts/switchyard-demo-helpdesk/src/main/resources/META-INF/persistence.xml
https://issues.jboss.org/browse/ENTESB-5032
=> ENTESB-5032  Heldesk demo not working on 1.3.x branch

quickstarts/switchyard-bpm-service/src/test/resources/xml/soap-response.xml
https://issues.jboss.org/browse/ENTESB-5222
=> ENTESB-5222 WebService test on bpm-service quickstart failing

fuse-integration-bom/pom.xml, pom.xml
https://issues.jboss.org/browse/ENTESB-5227
=> ENTESB-5227 Upgrade integration-parent bom on fuse-bxms-integ

README.md, quickstarts/jbpm-workitems-camel/ReadMe.md, quickstarts/spring-camel-drools-decision-table/ReadMe.md, quickstarts/switchyard-bpm-service/Readme.md, quickstarts/switchyard-demo-helpdesk/Readme.md, quickstarts/switchyard-demo-library/Readme.md, quickstarts/switchyard-drools-channels/Readme.md, quickstarts/switchyard-rules-camel-cbr/Readme.md, quickstarts/switchyard-rules-csv/ReadMe.md, quickstarts/switchyard-rules-interview-container/Readme.md, quickstarts/switchyard-rules-interview-dtable/Readme.md, quickstarts/switchyard-rules-interview/Readme.md, quickstarts/switchyard-rules-multithreaded/Readme.md
https://issues.jboss.org/browse/ENTESB-5318
=> ENTESB-5318 Include Drools EAP installer description on README files

fuse-integration-bom/pom.xml, pom.xml
https://issues.jboss.org/browse/ENTESB-5372
=> ENTESB-5372 Upgrade ip-bom version to 6.0.6

quickstarts/blueprint-camel-drools-decision-table/ReadMe.md, quickstarts/jbpm-workitems-camel/ReadMe.md, quickstarts/spring-camel-drools-decision-table/ReadMe.md, quickstarts/switchyard-bpm-service/Readme.md, quickstarts/switchyard-demo-helpdesk/Readme.md, quickstarts/switchyard-demo-library/Readme.md, quickstarts/switchyard-drools-channels/Readme.md, quickstarts/switchyard-rules-camel-cbr/Readme.md, quickstarts/switchyard-rules-csv/ReadMe.md, quickstarts/switchyard-rules-interview-container/Readme.md, quickstarts/switchyard-rules-interview-dtable/Readme.md, quickstarts/switchyard-rules-interview/Readme.md, quickstarts/switchyard-rules-multithreaded/Readme.md, release/karaf/distro/README_FUSE_INTEGRATION.md
https://issues.jboss.org/browse/ENTESB-5377
=> ENTESB-5377 Wrong command in IP quickstart Readmes

pom.xml
https://issues.jboss.org/browse/ENTESB-5386
=> ENTESB-5386 fix upgrade ip-bom dependency

pom.xml, quickstarts/switchyard-rules-camel-cbr/pom.xml, release/eap/config/pom.xml, release/eap/config/src/main/java/org/jboss/integration/fuse/config/FuseIntegrationConfigPlugin.java, release/eap/config/src/test/java/org/jboss/integration/fuse/config/StandaloneConfigTest.java, release/eap/config/src/test/resources/standalone.xml
https://issues.jboss.org/browse/ENTESB-5373
=> ENTESB-5373

quickstarts/blueprint-camel-drools-decision-table/pom.xml, quickstarts/jbpm-workitems-camel/pom.xml, quickstarts/spring-camel-drools-decision-table/pom.xml
https://issues.jboss.org/browse/ENTESB-5423
=> ENTESB-5423 Include Camel-bom on kie-camel quickstarts

release/eap/modules/src/main/resources/org/fuse/integration/switchyard/components/common/knowledge/resources/module.xml
https://issues.jboss.org/browse/ENTESB-5541?filter=12311122&jql=assignee%20%3D%20currentUser()%20ORDER%20BY%20created%20DESC
=> ENTESB-5541 IntPack on EAP, IBM java, BPM persistence, ClassNotFoundException: org.osgi.framework.Bundle

fuse-integration-bom/pom.xml, pom.xml, quickstarts/switchyard-bpm-service/pom.xml, quickstarts/switchyard-demo-helpdesk/pom.xml, quickstarts/switchyard-demo-library/pom.xml, quickstarts/switchyard-drools-channels/pom.xml, quickstarts/switchyard-rules-camel-cbr/pom.xml, quickstarts/switchyard-rules-csv/pom.xml, quickstarts/switchyard-rules-interview-container/pom.xml, quickstarts/switchyard-rules-interview-dtable/pom.xml, quickstarts/switchyard-rules-interview/pom.xml, quickstarts/switchyard-rules-loading/pom.xml, quickstarts/switchyard-rules-multithreaded/pom.xml, release/karaf/itests/switchyard/pom.xml
https://issues.jboss.org/browse/ENTESB-5698
=> ENTESB-5698 Remove 6.2.1 profile in the 1.4.x branch and 1.5.x branch

quickstarts/blueprint-camel-drools-decision-table/ReadMe.md, quickstarts/spring-camel-drools-decision-table/ReadMe.md
https://issues.jboss.org/browse/ENTESB-5665
=> ENTESB-5665 Integration Pack: fix CXF version clash in quickstarts poms

quickstarts/switchyard-rules-loading/Readme.md, quickstarts/switchyard-rules-loading/src/test/java/org/switchyard/quickstarts/rules/loading/HttpClient.java
https://issues.jboss.org/browse/ENTESB-5394
=> ENTESB-5394 Add installation instructions for "switchyard-rules-loading" quickstart in Readme.md

release/eap/modules/assembly.xml, release/karaf/distro/assembly.xml
https://issues.jboss.org/browse/ENTESB-6121
=> ENTESB-6121 Remove backward-compat from assembly
